{
    "title": "Site Title - src/_data/site.yml",
    "description": "Site Description - src/_data/site.yml",
    "url": "Site url - src/_data/site.yml",
    "lang": "en",
    "locale": "en_us",
    "author": "Site Author - src/_data/site.yml",
    "og_image_alt": "".
    "twitter": "",
    "linkedin": "",
    "facebook": "",
    "instagram": ""
}